name: Test

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          SENDINBLUE_API_KEY: ${{secrets.SENDINBLUE_API_KEY}}
